export default [
  {
    _id: '1234',
    name: 'CS1234 React JS',
    title: 'React JS',
    description: 'Full Stack software developer',
    image: '/images/reactjs.jpg',
  },
 {
    _id: '5610',
    name: 'CS5610 Web Development',
    title: 'Web Development',
    description: 'Full Stack software development',
    image: '/images/webdev.jpg',
  },
  {
    _id: '5200',
    name: 'CS5200 Database Management',
    title: 'Database Management',
    description: 'Relational and NoSQL databases',
    image: '/images/database.jpg',
  },
  {
    _id: '5500',
    name: 'CS5500 Algorithms',
    title: 'Algorithms',
    description: 'Algorithm design and analysis',
    image: '/images/algorithms.jpg',
  },
  {
    _id: '5800',
    name: 'CS5800 Data Structures',
    title: 'Data Structures',
    description: 'Advanced data structures',
    image: '/images/datastructures.jpg',
  },
  {
    _id: '5340',
    name: 'CS5340 Human Computer Interaction',
    title: 'Human Computer Interaction',
    description: 'User interface design',
    image: '/images/hci.jpg',
  },
  {
    _id: '5100',
    name: 'CS5100 Artificial Intelligence',
    title: 'Artificial Intelligence',
    description: 'Introduction to AI concepts',
    image: '/images/ai.jpg',
  },
]
